sudo: required

language: cpp

os:
  - linux
  - osx

compiler:
  - clang++
  - g++

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
    else
      brew update;
    fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get -qq install gcc-5 g++-5;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90;
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90;
      wget http://ftp.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz;
      tar xf lcov_1.11.orig.tar.gz;
      sudo make -C lcov-1.11/ install;
    else
      brew tap homebrew/versions;
      brew install gcc5;
      brew install lcov;
      if [ "$CC" = "gcc" ]; then
        export CC=gcc-5;
        export CXX=g++-5;
      fi
    fi
  - gem install coveralls-lcov;
  - $CC --version;
  - $CXX --version;
  - lcov --version;

before_script:
  - git submodule update --init --recursive

script:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      make test-coverage COVIGNORE="*/helper/*";
    else
      make test;
    fi

after_success:
- if [ $TRAVIS_OS_NAME = linux ]; then
    coveralls-lcov --repo-token ThN9JAPkYk61L9an6g80s3c3QIj9ORtq3 coverage/test/test.info;
  fi

env:
  global:
    - secure: JaaaKGDY+6k1AutLv0S8UVrzJUjaFz8Ly25mLzjLHBeqmApFBzwp0mgkgAakQAYbprp8VKiJ/SxTEvYS+ScjYamnSzymmwBjWb5bmJSL5JgY1HkWZ9o1kt8Fpv5S237hEVN4rDl3m37n8dqe7gpTCVSaFtZNQ8/WUWp+RwddonY=

addons:
  coverity_scan:
    project:
      name: topsframework/tops-refactoring
      description: Build submitted via Travis CI
    notification_email: renato.cferreira@hotmail.com
    build_command_prepend: make distclean
    build_command: make -O -j 2
    branch_pattern: coverity_scan
