language: cpp

compiler:
  - gcc

before_install:
  # for gcc with C++11 support
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get -qq update

install:
  # update to gcc with C++11 support
  - sudo apt-get -qq install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  # install boost for developers
  - sudo apt-get install libboost1.57-all-dev
  # install latest LCOV (1.9 was failing)
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - lcov --version
  - g++ --version

before_script:
  - git submodule update --init --recursive

script:
  - make test-coverage

after_success:
  - coveralls-lcov --repo-token ThN9JAPkYk61L9an6g80s3c3QIj9ORtq3 
                   coverage/data/test/test.info
